<?php

//=======================================================================
// A crawler for getting electricity energy market data from tsetmc.com.
// Developed by Saeid.S.Nobakht
//=======================================================================

//namespace App\Providers;
namespace NR\SymbolCrawler;

use Illuminate\Support\ServiceProvider;

class SymbolCrawlServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //
        $this->app->bind('symbolCrawler', function ($app) {
            return new SymbolCrawler();
        });
    }

    public function provides()
    {
        return array('symbolCrawler');
        //return parent::provides(); // TODO: Change the autogenerated stub
    }
}
